"""Prompts package."""

from .twin_persona import (
    TWIN_SYSTEM_PROMPT,
    SHADE_MODIFIER,
    PROFILE_BUILDER_PROMPT,
    TRAIT_EXTRACTION_PROMPT,
    MATCH_EXPLANATION_PROMPT,
    AGENT_REPORT_PROMPT,
)

__all__ = [
    "TWIN_SYSTEM_PROMPT",
    "SHADE_MODIFIER",
    "PROFILE_BUILDER_PROMPT",
    "TRAIT_EXTRACTION_PROMPT",
    "MATCH_EXPLANATION_PROMPT",
    "AGENT_REPORT_PROMPT",
]
